### ISSUE TITLE
Create a landing page with a directory of public topics to vote on 

### ISSUE THREAD

**Issue by Aminy16** [chingu-voyages/v36-toucans-team-02#14]

**Comment by Aminy16** [comment]
- [ ] To implement the UI development for the first page 

- [ ] Individual page for each topic that are connected through the ID

- [ ] Add vote button, on click the vote adds by one

**Comment by Aminy16** [comment]
Create a Header

**Comment by Aminy16** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/v36-toucans-team-02-61d4310987552b0011b158e4/issues/chingu-voyages/v36-toucans-team-02/14?planning-poker) with ZenHub @daveeedu

**Comment by Aminy16** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/v36-toucans-team-02-61d4310987552b0011b158e4/issues/chingu-voyages/v36-toucans-team-02/14?planning-poker) with ZenHub @Oreofeje

**Comment by Aminy16** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/v36-toucans-team-02-61d4310987552b0011b158e4/issues/chingu-voyages/v36-toucans-team-02/14?planning-poker) with ZenHub @mehmetalicakir

**Comment by Aminy16** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/v36-toucans-team-02-61d4310987552b0011b158e4/issues/chingu-voyages/v36-toucans-team-02/14?planning-poker) with ZenHub @strakins

**Comment by Oreofeje** [comment]
I did add some points to the #14 issue but I am not too sure that fulfills the request to “Please add your planning poker estimate with ZenHub”.Let me know what you think. Thanks.  Sent from Mail for Windows From: ArmineSent: Monday, January 17, 2022 6:45 PMTo: chingu-voyages/v36-toucans-team-02Cc: Oreofe; AssignSubject: Re: [chingu-voyages/v36-toucans-team-02] Users will see a directory of public topics to vote on (Issue #14) Please add your planning poker estimate with ZenHub @strakins—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by Aminy16** [comment]
Header- Oreofe 
Links to pages- David 
Create tasks

**Comment by Aminy16** [comment]
Had separate pages - Blessing and David

**Comment by Aminy16** [comment]
- [ ] Header will have logo to go back to home 

- [ ] Will have sections to add topics for private and public types 

- [ ] Button for login/sign up
